### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by rhagarty** [IBM/predict-opioid-prescribers#8]
1) in first sentence, can we change '(DSX)' to 'IBM Data Science Experience (DSX)' since it's the first time it's mentioned.
2) notebook URL in 'Create the Notebook' step is wrong. 'Opiod' is spelled wrong in the link.
3) is there any way to add a quick note about 'scikit learn' in the description? What is it and what value does it bring to the journey?

**Comment by MadisonJMyers** [comment]
1. Done!
2. Corrected the link.
3. Added a brief description- let me know if that works. I'm happy to add more if it's needed.
