### ISSUE TITLE
notebook issues

### ISSUE THREAD

**Issue by rhagarty** [IBM/predict-opioid-prescribers#9]
1) If I run the notebook and I start by importing the data assets, I wind up with duplicate df_data_X define statements, since they are already in your notebook.  
2) Can you add a little description to the last cell? I see the graph but not sure what it is telling me.

**Comment by MadisonJMyers** [comment]
Can you help guide me through your steps. Are you starting a new notebook or going off of my original one? If you are going off of the original, is the data already in the notebook? If so, I'll clarify not to add it if you're using the original notebook. And sure, I can add a description to the last cell!

**Comment by MadisonJMyers** [comment]
Addressed #2 but not sure about the data yet- will wait on more info.

**Comment by rhagarty** [comment]
@MadisonJMyers - re: #1. I am creating a new notebook and pointing to your notebook in the repo. When I start it up, it has all of the 'df_data_X' commands already in place, but it does NOT have the function 'get_object_storage_file_with_credentials_X'. So I need to import the data assets to get that. But that also brings along the duplicate 'df_data_x' commands. 

The other difference is that when I import the data assets, the 'df_data' command has different params that match my DSX project name. Not sure if this is relevant, but here is the diff:

// what comes with the notebook
df_data_1 = pd.read_csv(get_object_storage_file_with_credentials_97ff18b62fe74e0496a8cb3fe9eaa15b('USOpiatePredictions', 'opioids.csv'))

// what I get with the import - project name is 'opiodnotebook'
df_data_4 = pd.read_csv(get_object_storage_file_with_credentials_206e27f47669440cbe511e176ae8cb49('opiodnotebook', 'opioids.csv'))

**Comment by MadisonJMyers** [comment]
Ah ok now I understand. Alright I'll fix this today! Don't think we can get around it doing that, but I can explain to readers what's happening and how to go around it. Thanks Rich!

**Comment by rhagarty** [comment]
@MadisonJMyers - maybe we can add some comments to the notebook. So the issue is when the user creates and runs their own version of the notebook and then inserts the Pandas (3 of them). Once the insert is done, the notebook will have duplicate 'df_data_X' objects. You have already discussed in the README that you need to rename the inserted objects to '_1', '_2', and '_3', but the user STILL needs to  delete the original objects in the notebook. Maybe in cells [2], [3] and [4], you can add a comment that says something like:

# if inserted Pandas DataFrame, skip or delete this cell

**Comment by MadisonJMyers** [comment]
@rhagarty see PR. Was out yesterday so just got to this today! Let me know if this works for you.
